### Register
POST http://localhost:3333/users/register
Content-Type: application/json

{
  "name": "João Silva",
  "email": "joao@email.com",
  "password": "123456"
}

### Login
POST http://localhost:3333/users/login
Content-Type: application/json

{
  "email": "joao@email.com",
  "password": "123456"
}